/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import io.github.stefanbratanov.jvm.openai.*;

import java.util.ArrayList;
import java.util.List;

public class ChatService {
    public String callOpenAi(List<String> previousMessages, String userMessage){
        var apiKey ="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";
        var builder = OpenAI.newBuilder(apiKey);
        OpenAI openAI = builder.build();
        ChatClient chatClient = openAI.chatClient();
        List<ChatMessage> chatMessages = new ArrayList<>();
        for (String previousMessage : previousMessages) {
            chatMessages.add(ChatMessage.userMessage(previousMessage));
        }
        chatMessages.add(ChatMessage.userMessage(userMessage));

        CreateChatCompletionRequest createChatCompletionRequest = CreateChatCompletionRequest.newBuilder()
                .model("gpt-3.5-turbo")
                .messages(chatMessages)
                .build();

        ChatCompletion chatCompletion = chatClient.createChatCompletion(createChatCompletionRequest);
        var choices = chatCompletion.choices();
        return choices.iterator().next().message().content();
    }
}
