/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ChatServiceTest {
    @Test void appHasAGreeting() {
        ChatService classUnderTest = new ChatService();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
